@eval module $(gensym())
using TensorNetworkQuantumSimulator
const TN = TensorNetworkQuantumSimulator
using Test: @testset, @test
using NamedGraphs: neighbors
using NamedGraphs.GraphsExtensions: subgraph, degree, is_connected

# induced-degree helper for assertions
_min_induced_degree(g, S) = minimum(degree(subgraph(g, collect(S)), v) for v in S)

@testset "Loop cluster expansion graph core" begin

    # -----------------------------------------------------------------------
    # generation: loop clusters are connected, leaf-free, contain the target,
    # respect the size bound, and are generated by local growth (so a clipped
    # boundary cannot manufacture extra clusters).
    # -----------------------------------------------------------------------
    @testset "loop_clusters structural properties" begin
        g = named_grid((7, 7))
        target = Set([(4, 4), (4, 5)])
        for C in (3, 4, 5, 6, 7)
            cls = loop_clusters(g, target, C)
            for S in cls
                @test issubset(target, S)             # contains observable support
                @test length(S) <= C                  # size bound
                @test length(S) >= 3                  # smallest loop is a triangle
                @test is_connected(subgraph(g, collect(S)))
                @test _min_induced_degree(g, S) >= 2  # leaf-free
            end
            @test allunique(cls)
        end
        # square lattice: only plaquettes (4) up to C=5; 2 contain a given bond
        @test length(loop_clusters(g, target, 5)) == 2
        @test all(length(S) == 4 for S in loop_clusters(g, target, 5))
        # at C=6 the seven 2x3 blocks containing the bond appear alongside the 2 plaquettes
        @test length(loop_clusters(g, target, 6)) == 9
        @test count(S -> length(S) == 6, loop_clusters(g, target, 6)) == 7
    end

    # -----------------------------------------------------------------------
    # intersection closure: every pairwise intersection is present, and (since
    # all loop clusters share the target) every region still contains it.
    # -----------------------------------------------------------------------
    @testset "close_under_intersection" begin
        g = named_grid((7, 7))
        target = Set([(4, 4), (4, 5)])
        regions = close_under_intersection(push!(loop_clusters(g, target, 6), target))
        for r in regions, s in regions
            inter = intersect(r, s)
            @test isempty(inter) || inter in regions
        end
        @test all(issubset(target, r) for r in regions)
    end

    # -----------------------------------------------------------------------
    # counting numbers: partition of unity (Σ c(r) = 1) is the key invariant,
    # and the hand-computed square-lattice values must match exactly.
    # -----------------------------------------------------------------------
    @testset "counting numbers, square lattice bond" begin
        g = named_grid((7, 7))
        target = Set([(4, 4), (4, 5)])

        # C=2: single-cluster (BP) baseline only
        c2 = cluster_counting_numbers(g, target, 2)
        @test length(c2) == 1
        @test c2[target] == 1

        # C=4: two plaquettes (+1), shared bond (-1)
        c4 = cluster_counting_numbers(g, target, 4)
        @test sum(values(c4)) == 1
        @test sort([cc for (r, cc) in c4 if length(r) == 4]) == [1, 1]
        @test c4[target] == -1

        # C=6: seven 2x3 blocks (+1), two plaquettes (-3); bond region prunes to c=0
        c6 = cluster_counting_numbers(g, target, 6)
        @test sum(values(c6)) == 1
        @test sort([cc for (r, cc) in c6 if length(r) == 6]) == fill(1, 7)
        @test sort([cc for (r, cc) in c6 if length(r) == 4]) == [-3, -3]
        @test !haskey(c6, target)            # pruned: counting number went to zero
    end

    @testset "counting numbers, square lattice site" begin
        g = named_grid((7, 7))
        target = Set([(4, 4)])
        # bulk site: 4 plaquettes (+1), site core (-3)
        c4 = cluster_counting_numbers(g, target, 4)
        @test sum(values(c4)) == 1
        @test c4[target] == -3
        @test sort([cc for (r, cc) in c4 if length(r) == 4]) == fill(1, 4)
        # C=6: 12 blocks (+1), 4 plaquettes (-3), site core (+1)
        c6 = cluster_counting_numbers(g, target, 6)
        @test sum(values(c6)) == 1
        @test sort([cc for (r, cc) in c6 if length(r) == 6]) == fill(1, 12)
        @test sort([cc for (r, cc) in c6 if length(r) == 4]) == fill(-3, 4)
        @test c6[target] == 1
    end

    # -----------------------------------------------------------------------
    # partition-of-unity must hold on the honeycomb (z=3) too, across sizes.
    # -----------------------------------------------------------------------
    @testset "partition of unity, honeycomb" begin
        g = named_hexagonal_lattice_graph(4, 4)
        v = first(vertices(g))
        w = first(collect(neighbors(g, v)))
        for C in (6, 8, 10, 12)
            for target in (Set([v]), Set([v, w]))
                c = cluster_counting_numbers(g, target, C)
                @test sum(values(c)) == 1
                @test all(cc != 0 for cc in values(c))       # zeros are pruned
                @test all(issubset(target, r) for r in keys(c))
            end
        end
    end

    # -----------------------------------------------------------------------
    # tree-reduction: a region with a tree appendage collapses to its loopy
    # core, except where the appendage carries the protected observable site.
    # -----------------------------------------------------------------------
    @testset "loopy_core" begin
        g = named_grid((5, 5))
        plaquette = Set([(2, 2), (2, 3), (3, 2), (3, 3)])
        # appendage hanging off the plaquette
        with_tail = union(plaquette, Set([(1, 2)]))
        @test loopy_core(g, with_tail, Set{Tuple{Int,Int}}()) == plaquette
        # protecting the appendage site keeps it
        @test loopy_core(g, with_tail, Set([(1, 2)])) == with_tail
        # a pure tree reduces to just the protected target
        path = Set([(1, 1), (1, 2), (1, 3)])
        @test loopy_core(g, path, Set([(1, 2)])) == Set([(1, 2)])
    end
end
end
