#!/usr/bin/env python3
"""Plot the CTMRG-vs-boundary-MPS datasets, one figure per CSV.

Mirrors two figures of the "Matrix Product Belief Propagation" draft:

  ctm_vs_bmps_ising11_h0.01.csv     their Fig. 3 -- clean 11x11 Ising in a field,
                                    corner and centre, plus the d_X Z residual
  ctm_vs_bmps_rbim10_nishimori.csv  their Fig. 2 -- 10x10 random-bond Ising at the
                                    Nishimori point, disorder-averaged with bands

Generated by examples/ctm_vs_bmps_ising_field.jl and examples/ctm_vs_bmps_rbim.jl.
The CSVs may sit beside this script or in ./data/.

    python3 plot_ctm_vs_bmps.py                 # BOTH figures, PNG beside each CSV
    python3 plot_ctm_vs_bmps.py --show          # and open a window for each
    python3 plot_ctm_vs_bmps.py --csv path.csv  # just one

Needs only numpy + matplotlib.
"""

import argparse
import csv
import pathlib
import sys

import matplotlib.pyplot as plt
import numpy as np

HERE = pathlib.Path(__file__).resolve().parent
DATASETS = ("ctm_vs_bmps_ising11_h0.01.csv",      # their Fig. 3 — clean Ising, two sites
            "ctm_vs_bmps_rbim10_nishimori.csv")   # their Fig. 2 — RBIM, disorder bands


def find(name):
    """A CSV may sit beside this script or in the repo's examples/data/."""
    return next((p for p in (HERE / name, HERE / "data" / name) if p.exists()), None)

# PLOT LABELS follow the collaborators' draft, not the code's option names, so the two
# can be read side by side:
#     SVD-CTMRG  <->  projector = :cut     (per-interface rank-chi truncation)
#     MPS-BP     <->  projector = :cycle   (four-corner cycle; the stationary one)
# NB the pairing is not symmetric: both are CTMRG. In the draft MP-BP is the
# fixed-point condition d_X Z = 0, and CTMRG is how they find it -- so 'MPS-BP' here
# means the CTMRG whose fixed point satisfies it. The code keeps :cut / :cycle.
#
# Categorical slots 1-3 of the reference palette, in fixed order. Colour follows the
# METHOD, so it stays put if a series is dropped.
CUT, CYCLE, BMPS = "#2a78d6", "#eb6834", "#1baf7a"
INK, INK_2, INK_3 = "#0b0b0b", "#52514e", "#8a8880"

# A relative error of exactly 0 cannot be drawn on a log axis. The reference is itself
# a ratio of two 11x11 contractions, so nothing below ~1e-14 is meaningful anyway;
# clip to the floor and shade that region rather than silently dropping points.
FLOOR = 1e-16
REF_FLOOR = 1e-14


def read_csv(path):
    if not path.exists():
        sys.exit(f"missing {path}\nGenerate it first with the matching Julia example:\n"
                 f"  examples/ctm_vs_bmps_ising_field.jl   -> ctm_vs_bmps_ising11_h0.01.csv\n"
                 f"  examples/ctm_vs_bmps_rbim.jl          -> ctm_vs_bmps_rbim10_nishimori.csv")
    with open(path) as fh:
        rows = list(csv.DictReader(r for r in fh if not r.startswith("#")))
    cols = {k: np.array([float(r[k]) for r in rows]) for k in rows[0]}
    cols["chi"] = cols["chi"].astype(int)
    return cols


def error_panel(ax, chi, series, title):
    """`series` entries are (label, y, colour) or (label, (y, lo, hi), colour).

    The banded form is used by the RBIM dataset, where y is a median over disorder
    realisations and lo/hi are the min/max across them.
    """
    for label, y, colour in series:
        if isinstance(y, tuple):
            y, lo, hi = y
            ax.fill_between(chi, np.clip(lo, FLOOR, None), np.clip(hi, FLOOR, None),
                            color=colour, alpha=0.16, lw=0, zorder=2)
        ax.plot(chi, np.clip(y, FLOOR, None), marker="o", markersize=5.5,
                linewidth=1.8, color=colour, label=label, clip_on=False, zorder=3)
    ax.axhspan(FLOOR, REF_FLOOR, color=INK_3, alpha=0.10, lw=0, zorder=0)
    ax.text(chi[-1], REF_FLOOR * 1.6, "exact-reference floor", ha="right", va="bottom",
            fontsize=7.5, color=INK_3)
    ax.set_yscale("log")
    ax.set_title(title, fontsize=10, color=INK, pad=8)
    ax.set_xlabel("bond dimension  $\\chi$", fontsize=9, color=INK_2)
    style(ax)


def style(ax):
    ax.grid(True, which="major", axis="both", color=INK_3, alpha=0.22, linewidth=0.6)
    ax.set_axisbelow(True)
    for side in ("top", "right"):
        ax.spines[side].set_visible(False)
    for side in ("left", "bottom"):
        ax.spines[side].set_color(INK_3)
        ax.spines[side].set_linewidth(0.8)
    ax.tick_params(colors=INK_2, labelsize=8, length=3, width=0.8)


def plot_one(csv_path, show=False):
    csv_path = pathlib.Path(csv_path)
    d = read_csv(csv_path)
    chi = d["chi"]

    # The RBIM dataset carries disorder bands (*_med/_lo/_hi) and a single site; the clean
    # Ising dataset carries two sites and no bands. One script, two schemas.
    if "cut_med" in d:
        fig, axes = plt.subplots(1, 2, figsize=(9.0, 4.1), constrained_layout=True)
        fig.patch.set_facecolor("#fcfcfb")
        for ax in axes:
            ax.set_facecolor("#fcfcfb")
        error_panel(axes[0], chi,
                    [("SVD-CTMRG", (d["cut_med"], d["cut_lo"], d["cut_hi"]), CUT),
                     ("MPS-BP", (d["cycle_med"], d["cycle_lo"], d["cycle_hi"]), CYCLE),
                     ("boundary MPS", (d["bmps_med"], d["bmps_lo"], d["bmps_hi"]), BMPS)],
                    "RBIM 10x10, site (4,4)")
        axes[0].set_ylabel(r"$|\delta m| / |m|$", fontsize=9, color=INK_2)
        axes[1].axis("off")
        axes[1].text(0.0, 0.5,
                     "median over 5 disorder realisations;\n"
                     "band = min-max across them.\n\n"
                     "Negative bonds make the network\n"
                     "strongly non-Hermitian -- the regime\n"
                     "the draft picks the RBIM for.\n\n"
                     "bMPS floor is ACCUMULATION in the\n"
                     "global Z, not a truncation limit\n"
                     "-- see the CSV header.",
                     fontsize=8.5, color=INK_2, va="center", ha="left")
        for ax in axes[:1]:
            ax.legend(frameon=False, fontsize=8.5, labelcolor=INK_2, handlelength=1.6)
        fig.suptitle("Finite 10x10 random-bond Ising at the Nishimori point, $h=0.01$ — "
                     "CTMRG vs boundary MPS", fontsize=11, color=INK)
        out = csv_path.with_suffix(".png")
        fig.savefig(out, dpi=200, facecolor=fig.get_facecolor())
        print(f"wrote {out}")
        if show:
            plt.show()
        return

    fig, axes = plt.subplots(1, 3, figsize=(12.4, 4.1), constrained_layout=True)
    fig.patch.set_facecolor("#fcfcfb")
    for ax in axes:
        ax.set_facecolor("#fcfcfb")

    error_panel(axes[0], chi,
                [("SVD-CTMRG", d["cut_corner"], CUT),
                 ("MPS-BP", d["cycle_corner"], CYCLE),
                 ("boundary MPS", d["bmps_corner"], BMPS)],
                "CORNER site (1,1)")
    axes[0].set_ylabel(r"$|\delta m| / |m|$", fontsize=9, color=INK_2)

    error_panel(axes[1], chi,
                [("SVD-CTMRG", d["cut_centre"], CUT),
                 ("MPS-BP", d["cycle_centre"], CYCLE),
                 ("boundary MPS", d["bmps_centre"], BMPS)],
                "CENTRE site (6,6)")

    # Separate panel, not a second y-axis: this is a different quantity. bMPS has no
    # analogue, so only two series appear here.
    ax = axes[2]
    ax.plot(chi, np.clip(d["marg_cut"], FLOOR, None), marker="o", markersize=5.5,
            linewidth=1.8, color=CUT, label="SVD-CTMRG", clip_on=False, zorder=3)
    ax.plot(chi, np.clip(d["marg_cycle"], FLOOR, None), marker="o", markersize=5.5,
            linewidth=1.8, color=CYCLE, label="MPS-BP", clip_on=False, zorder=3)
    ax.set_yscale("log")
    ax.set_title(r"stationarity residual  $\partial_X Z$", fontsize=10, color=INK, pad=8)
    ax.set_xlabel("bond dimension  $\\chi$", fontsize=9, color=INK_2)
    ax.set_ylabel("marginal_inconsistency", fontsize=9, color=INK_2)
    style(ax)

    for ax in axes:
        ax.legend(frameon=False, fontsize=8.5, labelcolor=INK_2, handlelength=1.6)

    fig.suptitle("Finite 11x11 classical Ising, $\\beta=0.4407$, $h=0.01$ — "
                 "CTMRG vs boundary MPS at matched $\\chi$",
                 fontsize=11, color=INK)

    out = csv_path.with_suffix(".png")
    fig.savefig(out, dpi=200, facecolor=fig.get_facecolor())
    print(f"wrote {out}")
    if show:
        plt.show()


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--show", action="store_true", help="also open a window per figure")
    ap.add_argument("--csv", default=None,
                    help="plot just this CSV (default: every dataset found)")
    args = ap.parse_args()

    if args.csv:
        plot_one(args.csv, args.show)
        return
    found = [(n, find(n)) for n in DATASETS]
    missing = [n for n, p in found if p is None]
    for name, path in found:
        if path is not None:
            plot_one(path, args.show)
    if missing:
        print("not found (skipped): " + ", ".join(missing))
        print("  generate with: julia --project=. --startup-file=no "
              "examples/ctm_vs_bmps_ising_field.jl   (and ..._rbim.jl)")
    if all(p is None for _, p in found):
        sys.exit("no datasets found next to this script or in ./data/")


if __name__ == "__main__":
    main()
