# Combinatorial core of the loop cluster expansion for local observables
# (Gray, Park, Evenbly, Pancotti, Kjønstad & Chan, arXiv:2510.05647, Algorithm 1,
# lines 4-13). This file is PURE GRAPH CODE: it never touches a tensor, knows
# nothing about fermions/bosons, and operates only on a NamedGraph and vertex sets.
#
# A "region" is a `Set` of vertices. Its geometry is the vertex-induced subgraph
# `subgraph(g, collect(region))`. A "loop cluster" is a connected region whose
# induced subgraph has no leaves (every vertex has induced degree >= 2).
#
# Pipeline (`cluster_counting_numbers`):
#   1. `loop_clusters`            -- generate loop clusters containing the target (line 4)
#   2. `close_under_intersection` -- add all pairwise intersections to fixpoint (line 5)
#   3. `region_counting_numbers`  -- c_r = 1 - sum_{a ⊋ r} c_a, decreasing |r| (line 6)
#   4. `loopy_core` + fold        -- tree-reduction: collapse to loopy core (lines 7-13)

# --- §2 generation: walks out from the observable region -----------------------

# All connected vertex subsets `S` with `target ⊆ S` and `|S| <= C`, grown outward
# from `target` by repeatedly adjoining a vertex adjacent to the current set. This
# is the "walk from the observable" enumeration: it only ever explores vertices
# reachable from the target within `C-1` steps, so the cost is set by the local
# neighbourhood, NOT the (possibly infinite/huge) global graph. Every connected
# superset of `target` is reachable this way (peel a non-cut vertex to see the
# reverse), and a `seen` set removes the duplicate growth orders.
function _connected_supersets(g::AbstractGraph, target::Set, C::Integer)
    V = vertextype(g)
    seed = Set{V}(target)
    is_connected(subgraph(g, collect(seed))) ||
        error("observable support $(collect(target)) must induce a connected subgraph")
    seen = Set{Set{V}}()
    out = Set{V}[]
    stack = Set{V}[seed]
    while !isempty(stack)
        S = pop!(stack)
        S in seen && continue
        push!(seen, S)
        push!(out, S)
        length(S) >= C && continue
        for v in S, w in neighbors(g, v)
            w in S || push!(stack, union(S, Set{V}((w,))))
        end
    end
    return out
end

# A region is a loop cluster iff its induced subgraph is connected and leaf-free
# (min induced degree >= 2). The smallest possible loop is a 3-cycle, so anything
# with < 3 vertices is rejected outright.
function _is_loop_cluster(g::AbstractGraph, S::Set)
    length(S) < 3 && return false
    sub = subgraph(g, collect(S))
    is_connected(sub) || return false
    return all(degree(sub, v) >= 2 for v in S)
end

"""
    loop_clusters(g, target, max_cluster_size) -> Vector{Set}

All loop clusters (connected, leaf-free vertex sets) of `g` that contain every
vertex of `target` and have at most `max_cluster_size` vertices. `target` is the
observable support: a single vertex set like `Set([v])`, or a bond `Set([i, j])`.
Generated by local growth out from `target` (see `_connected_supersets`).
"""
function loop_clusters(g::AbstractGraph, target, max_cluster_size::Integer)
    T = target isa Set ? target : Set(target)
    return filter(S -> _is_loop_cluster(g, S), _connected_supersets(g, T, max_cluster_size))
end

# --- §3 combinatorics: intersection closure + counting numbers -----------------

"""
    close_under_intersection(regions) -> Vector{Set}

Close a collection of regions under pairwise intersection (Algorithm 1, line 5):
repeatedly add `r_a ∩ r_b` until no new (non-empty) region appears. Intersections
need NOT be loops — they are the overlap regions whose over-counting the counting
numbers correct. If every input region contains a common target `T`, so does every
intersection, hence the closure stays `⊇ T`.
"""
function close_under_intersection(regions)
    R = Set(regions)
    frontier = collect(R)
    while !isempty(frontier)
        new_regions = eltype(frontier)[]
        rs = collect(R)
        for r in frontier, s in rs
            inter = intersect(r, s)
            if !isempty(inter) && inter ∉ R
                push!(R, inter)
                push!(new_regions, inter)
            end
        end
        frontier = unique(new_regions)
    end
    return collect(R)
end

"""
    region_counting_numbers(regions) -> Dict{Set, Int}

Inclusion-exclusion counting numbers (Algorithm 1, line 6): for each region `r`,
`c_r = 1 - Σ_{a ⊋ r} c_a`, where the sum runs over the proper supersets of `r`
present in `regions`. Evaluated in order of decreasing `|r|` so every superset's
counting number is already known. `regions` should already be closed under
intersection.
"""
function region_counting_numbers(regions)
    order = sort(collect(regions); by = length, rev = true)
    c = Dict{eltype(order), Int}()
    for (i, r) in enumerate(order)
        s = 0
        for j in 1:(i - 1)               # only strictly larger regions can be proper supersets
            a = order[j]
            length(a) > length(r) && issubset(r, a) && (s += c[a])
        end
        c[r] = 1 - s
    end
    return c
end

# --- tree-reduction (Algorithm 1, lines 7-13) ----------------------------------

# Connected components of the subgraph of `g` induced on the vertex set `S`, as a
# vector of vertex `Set`s. Plain BFS over `neighbors` restricted to `S` (the clusters
# are small, so this is cheap and avoids materializing a `subgraph`).
function _connected_components(g::AbstractGraph, S)
    remaining = Set(S)
    V = eltype(remaining)
    comps = Set{V}[]
    while !isempty(remaining)
        seen = Set{V}((first(remaining),))
        stack = collect(seen)
        while !isempty(stack)
            x = pop!(stack)
            for y in neighbors(g, x)
                (y in remaining && y ∉ seen) || continue
                push!(seen, y)
                push!(stack, y)
            end
        end
        push!(comps, seen)
        setdiff!(remaining, seen)
    end
    return comps
end

"""
    loopy_core(g, region, protect) -> Set

The "largest loop with equivalent BP contraction" (Algorithm 1, line 8). Two
reductions, applied to a fixpoint, both leave the region's BP-contracted ratio
`O_r` unchanged:

  * **strip leaves** (induced degree < 2): a tree appendage contracted with the
    converged BP messages reproduces exactly the BP message it hangs from, so it
    cancels between numerator and denominator;
  * **drop protect-free components**: a connected component carrying no observable
    site contracts to a scalar identical in numerator and denominator, so it
    cancels too. (Leaf-stripping can disconnect a region — e.g. severing a tree
    path between two loops — which is why this runs in the same fixpoint.)

Vertices in `protect` (the observable support) are never removed. Note that an
in-region **bridge to a loop** is *kept*: that loop imposes a non-BP message across
the bridge bond and genuinely shifts `O_r`, so it is not tree-like and must stay.
With an empty `protect` (no anchor) the component drop is skipped, leaving the bare
leaf-stripped 2-core.
"""
function loopy_core(g::AbstractGraph, region::Set, protect::Set)
    core = Set(region)
    while true
        sub = subgraph(g, collect(core))
        leaves = [v for v in core if v ∉ protect && degree(sub, v) < 2]
        if !isempty(leaves)
            setdiff!(core, leaves)
            continue
        end
        if !isempty(protect)
            comps = _connected_components(g, core)
            if length(comps) > 1
                keep = Set{eltype(core)}()
                for comp in comps
                    any(v -> v in protect, comp) && union!(keep, comp)
                end
                if length(keep) < length(core)
                    core = keep
                    continue
                end
            end
        end
        break
    end
    return core
end

"""
    cluster_counting_numbers(g, target, max_cluster_size) -> Dict{Set, Int}

Full graph-side loop cluster expansion accounting (Algorithm 1, lines 4-13) for an
observable supported on `target`:

  1. generate loop clusters containing `target` up to `max_cluster_size` sites,
  2. close them under intersection,
  3. assign inclusion-exclusion counting numbers,
  4. tree-reduce every region to its loopy core (protecting `target`) and fold the
     counting numbers of regions sharing a core,
  5. drop regions whose total counting number is zero.

Returns the surviving `region => counting_number` map. The contraction step (per
region: `O_r = ⟨Ψ|Ô|Ψ⟩_r / ⟨Ψ|Ψ⟩_r` with BP messages on ∂r) lives elsewhere; this
function is the combinatorics only.
"""
function cluster_counting_numbers(g::AbstractGraph, target, max_cluster_size::Integer)
    T = target isa Set ? target : Set(target)
    # Seed the target region itself: it is the single-cluster (BP) baseline with
    # counting number +1. It is not a loop, so `loop_clusters` never produces it; it
    # would only appear as an intersection once >=2 loops overlap. Seeding it makes the
    # minimal-`C` limit reduce to the ordinary BP expectation, and is a no-op whenever
    # the intersection closure would have produced it anyway.
    clusters = loop_clusters(g, T, max_cluster_size)
    regions = close_under_intersection(push!(clusters, T))
    c = region_counting_numbers(regions)

    reduced = Dict{eltype(regions), Int}()
    for (r, cr) in c
        core = loopy_core(g, r, T)
        reduced[core] = get(reduced, core, 0) + cr
    end
    return Dict(r => cr for (r, cr) in reduced if cr != 0)
end
