module TensorNetworkQuantumSimulator


include("imports.jl")

include("siteinds.jl")
include("Fermions/fermionic_tensors.jl")
include("TensorNetworks/abstracttensornetwork.jl")
include("TensorNetworks/tensornetwork.jl")
include("TensorNetworks/tensornetworkstate.jl")
include("TensorNetworks/tensornetworkstate_constructors.jl")
include("contraction_sequences.jl")
include("contract.jl")
include("Forms/abstractform.jl")
include("Forms/bilinearform.jl")
include("Forms/quadraticform.jl")
include("MessagePassing/abstractbeliefpropagationcache.jl")
include("MessagePassing/beliefpropagationcache.jl")
include("MessagePassing/boundarympscache.jl")
include("MessagePassing/LoopExpansion/graph_clusters.jl")
include("MessagePassing/LoopExpansion/loopcorrection.jl")
include("graph_ops.jl")
include("utils.jl")

include("Apply/apply_gates.jl")
include("Apply/simple_update.jl")
include("Apply/full_update.jl")
include("Apply/gate_definitions.jl")
include("expect.jl")
include("norm_sqr.jl")
include("inner.jl")
include("normalize.jl")
include("sampling.jl")
include("symmetric_gauge.jl")
include("entanglement.jl")
include("truncate.jl")
include("rdm.jl")

include("Fermions/ops.jl")
include("Fermions/fermionictensornetworkstate.jl")
include("Fermions/factorize_fermionic_tensors.jl")
include("Fermions/fermionic_gates.jl")
include("iTNS/infinite_tensornetworkstate.jl")
include("iTNS/apply_gate.jl")
include("iTNS/expect.jl")
include("iTNS/embed.jl")


export
    vertices,
    edges,
    add_edge,
    degree,
    apply_gates,
    apply_circuit,
    register_gate!,
    register_alias!,
    unregister_gate!,
    rem_vertex!,
    truncate,
    expect,
    is_tree,
    expect_boundarymps,
    expect_loopcorrect,
    ket_network,
    truncate,
    maxvirtualdim,
    siteinds,
    edge_color,
    zerostate,
    named_grid,
    sample,
    TensorNetworkState,
    tensornetworkstate,
    random_tensornetworkstate,
    random_fermionic_tensornetworkstate,
    fermionic_tensornetworkstate,
    FermionicITensor,
    fermionic_hopping_gate,
    fermionic_number_gate,
    fermionic_interaction_gate,
    fermionic_hopping_hamiltonian,
    fermionic_number_hamiltonian,
    fermionic_interaction_hamiltonian,
    fermionic_exp_gate,
    symmetric_svd,
    is_fermionic,
    contract,
    permute,
    dag,
    BeliefPropagationCache,
    rescale!,
    message,
    network,
    update,
    symmetric_gauge,
    symmetric_gauge!,
    messages,
    gauge_and_scale,
    identity_tensornetworkstate,
    random_tensornetwork,
    siteinds,
    inner,
    named_grid,
    named_comb_tree,
    named_hexagonal_lattice_graph,
    named_path_graph,
    neighbors,
    center,
    NamedGraph,
    graph,
    datatype,
    scalartype,
    BoundaryMPSCache,
    TensorNetwork,
    TensorNetworkState,
    AbstractTensorNetwork,
    partitionfunction,
    contract,
    TreeSA,
    GreedyMethod,
    SABipartite,
    Treewidth,
    ExactTreewidth,
    HyperND,
    norm_sqr,
    map_virtualinds,
    map_virtualinds!,
    map_tensors,
    map_tensors!,
    rem_vertex!,
    rem_vertex,
    src,
    dst,
    normalize,
    QuadraticForm,
    BilinearForm,
    sample_certified,
    sample_directly_certified,
    vertextype,
    virtualind,
    virtualinds,
    nv,
    heavy_hexagonal_lattice,
    rescale,
    von_neumann_entanglement_entropy,
    second_renyi_entanglement_entropy,
    build_graph_from_circuit,
    reduced_density_matrix,
    rdm,
    toriccode_groundstate,
    ising_partitionfunction,
    InfiniteTensorNetworkState,
    InfiniteTNS,
    infinite_tensornetworkstate,
    infinite_tns,
    infinite_fermionic_tensornetworkstate,
    infinite_fermionic_tns,
    coordination,
    iTNS_apply_gate,
    iTNS_expect,
    iTNS_reduced_density_matrix,
    NamedLattice,
    SquareLattice,
    HexagonalLattice,
    lattice_coordination,
    lattice_patch,
    embed,
    absorb_bonds
end
